version: "3.7"

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    image: nuxt_client_nuxt-app
    restart: always
    ports:
      # - "3000:3000"
      - "80:3000"
    # command: "npm run dev"
    command: "npm run dev"
    networks:
      - nuxt-network
networks:
  nuxt-network:
    driver: bridge
