version: "3.3"

services:
  nuxt-app:
    build: .
    container_name: nuxt-app
    image: nuxt_client_nuxt-app
    restart: always
    ports:
      # - "3000:3000"
      - "3000:3000"
    # command: "npm run dev"
    command: "npm run dev"
    networks:
      - nuxt-network
  web-server:
    image: nginx:1.17.10-alpine
    container_name: web-server
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - web-root:/var/www/blowstack
    ports:
      - 80:80
    networks:
      nuxt-network:
    depends_on:
      - nuxt-app
    restart: unless-stopped
volumes:
  web-root:
networks:
  nuxt-network:
    driver: bridge
